"""empty message

Revision ID: 20593285c206
Revises: ef5232d0bb06
Create Date: 2020-07-26 17:09:07.846791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20593285c206'
down_revision = 'ef5232d0bb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbooks', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbooks', 'status')
    # ### end Alembic commands ###
