"""empty message

Revision ID: 3f790bee9f16
Revises: 97c4102a6849
Create Date: 2020-08-12 17:17:55.335107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f790bee9f16'
down_revision = '97c4102a6849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('Logbooks', sa.Float(), nullable=False),
    sa.Column('pontos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pontos_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontors')
    # ### end Alembic commands ###
