"""empty message

Revision ID: 5fe19402ebea
Revises: 70a17dcae927
Create Date: 2020-08-12 17:22:04.374803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe19402ebea'
down_revision = '70a17dcae927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbooks', sa.Column('pontos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbooks', 'pontos')
    # ### end Alembic commands ###
