"""empty message

Revision ID: 70a17dcae927
Revises: 3f790bee9f16
Create Date: 2020-08-12 17:20:48.723543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a17dcae927'
down_revision = '3f790bee9f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pontos', sa.INTEGER(), nullable=True),
    sa.Column('Logbooks', sa.FLOAT(), nullable=False),
    sa.Column('pontos_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pontos_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
