"""empty message

Revision ID: 88e3e3f73330
Revises: f62060713f18
Create Date: 2020-08-12 17:46:14.073485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e3e3f73330'
down_revision = 'f62060713f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbooks', 'pontos')
    op.add_column('users', sa.Column('pontos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pontos')
    op.add_column('logbooks', sa.Column('pontos', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
