"""empty message

Revision ID: 8f785e0bc727
Revises: befb2a2ca516
Create Date: 2020-12-12 22:10:35.202324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f785e0bc727'
down_revision = 'befb2a2ca516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbooks', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbooks', sa.Column('status', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
