"""empty message

Revision ID: 97c4102a6849
Revises: 20593285c206
Create Date: 2020-08-12 17:14:04.945626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c4102a6849'
down_revision = '20593285c206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('Logbooks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos')
    # ### end Alembic commands ###
