"""empty message

Revision ID: 9eb2ad967daf
Revises: 2b3d99d99e4a
Create Date: 2020-12-28 17:35:46.499342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb2ad967daf'
down_revision = '2b3d99d99e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cont_tempo_str', sa.String(length=20000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cont_tempo_str')
    # ### end Alembic commands ###
