"""empty message

Revision ID: dba21cc29452
Revises: 88e3e3f73330
Create Date: 2020-08-12 17:50:51.937709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba21cc29452'
down_revision = '88e3e3f73330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logbooks', schema=None) as batch_op:
        batch_op.drop_column('pontos')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pontos')

    with op.batch_alter_table('logbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
