"""empty message

Revision ID: e8ce2dc07a4e
Revises: 
Create Date: 2021-01-09 20:32:09.260133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ce2dc07a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('destino', sa.String(length=120), nullable=True),
    sa.Column('p_data', sa.String(length=20), nullable=True),
    sa.Column('voo', sa.String(length=200), nullable=True),
    sa.Column('hora_partida', sa.String(length=120), nullable=True),
    sa.Column('hora_chegada', sa.String(length=120), nullable=True),
    sa.Column('aeronave', sa.String(length=120), nullable=True),
    sa.Column('gate', sa.String(length=120), nullable=True),
    sa.Column('piloto', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('destino', sa.String(length=120), nullable=True),
    sa.Column('p_data', sa.String(length=20), nullable=True),
    sa.Column('voo', sa.String(length=200), nullable=True),
    sa.Column('hora_partida', sa.String(length=120), nullable=True),
    sa.Column('hora_chegada', sa.String(length=120), nullable=True),
    sa.Column('aeronave', sa.String(length=120), nullable=True),
    sa.Column('gate', sa.String(length=120), nullable=True),
    sa.Column('piloto', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('destino', sa.String(length=120), nullable=True),
    sa.Column('p_data', sa.String(length=20), nullable=True),
    sa.Column('voo', sa.String(length=200), nullable=True),
    sa.Column('hora_partida', sa.String(length=120), nullable=True),
    sa.Column('hora_chegada', sa.String(length=120), nullable=True),
    sa.Column('aeronave', sa.String(length=120), nullable=True),
    sa.Column('gate', sa.String(length=120), nullable=True),
    sa.Column('piloto', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('sobrenome', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('registro', sa.String(length=200), nullable=True),
    sa.Column('ifcomunity', sa.String(length=400), nullable=True),
    sa.Column('sobremim', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=200), nullable=True),
    sa.Column('base', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=200), nullable=True),
    sa.Column('grau', sa.String(length=200), nullable=True),
    sa.Column('data_create', sa.DateTime(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('cont_tempo', sa.Float(), nullable=True),
    sa.Column('cont_tempo_str', sa.String(length=20000), nullable=True),
    sa.Column('cont_voo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('logbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saida', sa.String(length=200), nullable=True),
    sa.Column('chegada', sa.String(length=200), nullable=True),
    sa.Column('aeronave', sa.String(length=200), nullable=True),
    sa.Column('voo', sa.String(length=200), nullable=True),
    sa.Column('tempo', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logbooks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('eventos_3')
    op.drop_table('eventos_2')
    op.drop_table('eventos_1')
    # ### end Alembic commands ###
