"""empty message

Revision ID: f62060713f18
Revises: 5fe19402ebea
Create Date: 2020-08-12 17:45:39.238108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62060713f18'
down_revision = '5fe19402ebea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbooks', 'pontos')
    op.add_column('users', sa.Column('pontos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pontos')
    op.add_column('logbooks', sa.Column('pontos', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
